export const dummydata = [
  {
    period: "today",
    chats: [
      {
        timestamp: "2024-06-26T09:00:00Z",
        messages: 7,
        content: [
          "What are the current stock market trends?",
          "Can you explain the concept of dividend investing?",
          "How do I calculate return on investment (ROI)?",
          "Is there a fee for using your financial advisory services?",
          "Can I schedule a consultation with a financial analyst?",
          "What are the tax implications of capital gains?",
          "How can I protect my investments during market volatility?",
        ],
      },
      {
        timestamp: "2024-06-26T11:00:00Z",
        messages: 12,
        content: [
          "What are the steps to create a diversified investment portfolio?",
          "Can you recommend books on personal finance?",
          "How do I apply for a mortgage?",
          "Is it better to lease or buy a car?",
          "What are the latest updates on cryptocurrency regulations?",
          "Can I invest in mutual funds through your platform?",
          "What are your retirement planning services?",
          "How do I manage risk in my investment strategy?",
          "Do you offer financial planning for small businesses?",
          "What is your approach to sustainable investing?",
          "How can I improve my credit score?",
          "Can I get advice on estate planning?",
        ],
      },
      {
        timestamp: "2024-06-26T13:00:00Z",
        messages: 9,
        content: [
          "Do you provide insights on macroeconomic trends?",
          "How can I diversify my investment in international markets?",
          "What are the advantages of index funds?",
          "Can you explain the impact of inflation on savings?",
          "How do I open a retirement account?",
          "Is your platform secure for online transactions?",
          "What are the benefits of using a financial advisor?",
          "Do you offer guidance on student loans?",
          "Can I invest in real estate through your services?",
        ],
      },
    ],
  },
  {
    period: "yesterday",
    chats: [
      {
        timestamp: "2024-06-25T10:00:00Z",
        messages: 5,
        content: [
          "How do I diversify my investment portfolio?",
          "Can you explain the concept of compound interest?",
          "What are the risks of day trading?",
          "Is there a minimum investment requirement?",
          "How can I save for my child's education?",
        ],
      },
      {
        timestamp: "2024-06-25T12:00:00Z",
        messages: 8,
        content: [
          "What are the tax implications of owning rental property?",
          "Can I get advice on budgeting and saving?",
          "How do I choose between stocks and bonds?",
          "What are the latest trends in financial technology (FinTech)?",
          "Do you provide analysis on market sectors?",
          "How can I prepare for retirement?",
          "What are your views on sustainable investing?",
          "Can I automate my investment contributions?",
        ],
      },
      {
        timestamp: "2024-06-25T14:00:00Z",
        messages: 10,
        content: [
          "How do I evaluate the performance of a mutual fund?",
          "Can you recommend strategies for wealth preservation?",
          "What are the benefits of a diversified retirement portfolio?",
          "How can I reduce investment fees?",
          "Do you offer guidance on managing debt?",
          "What are your thoughts on investing in emerging markets?",
          "Can I get advice on charitable giving?",
          "How do I protect my assets in a volatile market?",
          "Is it advisable to invest in commodities?",
          "What are your services for high-net-worth individuals?",
        ],
      },
    ],
  },
  {
    period: "previous_7_days",
    chats: [
      {
        timestamp: "2024-06-24T10:00:00Z",
        messages: 6,
        content: [
          "How do I evaluate the financial health of a company?",
          "Can I get insights on corporate governance?",
          "What are the risks of leveraged investing?",
          "How can I hedge against currency fluctuations?",
          "Do you provide analysis on economic indicators?",
          "Can you explain the impact of interest rates on investments?",
        ],
      },
      {
        timestamp: "2024-06-23T12:00:00Z",
        messages: 7,
        content: [
          "What are the advantages of exchange-traded funds (ETFs)?",
          "Can you explain the principles of value investing?",
          "How do I build an emergency fund?",
          "Do you provide analysis on global markets?",
          "What are the steps to financial independence?",
          "Can I get advice on portfolio rebalancing?",
          "How can I protect my investments during a recession?",
        ],
      },
      {
        timestamp: "2024-06-22T14:00:00Z",
        messages: 9,
        content: [
          "How do I assess the risk-return profile of an investment?",
          "Can you recommend strategies for tax-efficient investing?",
          "What are the benefits of long-term investing?",
          "How can I spot investment scams?",
          "Do you offer insights on retirement income planning?",
          "Can I get advice on philanthropic investing?",
          "What are your views on impact investing?",
          "How do I choose a financial advisor?",
          "Can I invest in alternative assets through your platform?",
        ],
      },
      {
        timestamp: "2024-06-21T10:00:00Z",
        messages: 4,
        content: [
          "How do I navigate the stock market during political uncertainty?",
          "Can you explain the role of central banks in the economy?",
          "What are the key factors influencing interest rates?",
          "Do you provide analysis on market cycles?",
        ],
      },
      {
        timestamp: "2024-06-20T12:00:00Z",
        messages: 8,
        content: [
          "How can I build a diversified retirement income portfolio?",
          "Can you recommend resources for financial education?",
          "What are the risks of investing in bonds?",
          "How do I create a financial plan for major life events?",
          "Do you offer guidance on estate and inheritance planning?",
          "Can I get advice on managing a windfall?",
          "What are your views on sustainable business practices?",
          "How can I evaluate the financial stability of an insurance company?",
        ],
      },
      {
        timestamp: "2024-06-19T14:00:00Z",
        messages: 11,
        content: [
          "How do I analyze the balance sheet of a company?",
          "Can you explain the factors affecting stock prices?",
          "What are the key metrics for evaluating mutual funds?",
          "Do you provide analysis on industry sectors?",
          "How can I calculate my net worth?",
          "Can I get advice on investment psychology?",
          "What are the risks of investing in emerging markets?",
          "How do I choose between active and passive investing?",
          "Do you offer guidance on financial risk management?",
          "Can you explain the impact of geopolitical events on investments?",
          "What are the steps to building generational wealth?",
        ],
      },
    ],
  },
];
